server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: card-aggregate
              uri: lb://card-aggregate-service
              predicates:
                - Path=/card-aggregate-service/**
              filters:
                - StripPrefix=1

            - id: card-aggregate-swagger-ui
              uri: lb://card-aggregate-service
              predicates:
                - Path=/openapi/**

            - id: card
              uri: lb://card-service
              predicates:
                - Path=/cards/**

            - id: transaction
              uri: lb://transaction-service
              predicates:
                - Path=/transactions/**

            - id: eureka-api
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/api/{segment}
              filters:
                - SetPath=/eureka/{segment}

            - id: eureka-web-start
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/web
              filters:
                - SetPath=/

            - id: eureka-web-other
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/**

            - id: host_route_200
              uri: http://httpstat.us
              predicates:
                - Host=i.feel.lucky:8080
                - Path=/headerrouting/**
              filters:
                - SetPath=/200

            - id: host_route_418
              uri: http://httpstat.us
              predicates:
                - Host=im.a.teapot:8080
                - Path=/headerrouting/**
              filters:
                - SetPath=/418

            - id: host_route_501
              uri: http://httpstat.us
              predicates:
                - Path=/headerrouting/**
              filters:
                - SetPath=/501

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

---
spring:
  config:
    activate:
      on-profile: docker
  main:
    allow-bean-definition-overriding: true

app:
  eureka-server: eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
